#!/bin/sh
## Configuracion personal dnf
printf "%s" "
defaultyes=True
fastestmirror=True
max_parallel_downloads=20
" | sudo tee -a /etc/dnf/dnf.conf
## Eliminar Paquetes no necesarios
sudo dnf remove libreoffice\* tigervnc-server-minimal ibus skanpage akregator kmail kontact korganizer ktnef \
                kaddressbook kcharselect kfind kgpg kmousetool kmouth kwrite filelight anaconda\* b43\* \
                mediawriter nano nano-default-editor vpnc openconnect openvpn dragon dnfdragora elisa-player \
                kamoso konversation kamera kmag gtk2 audiocd-kio  
## Remover dependencias inecesarias
sudo dnf autoremove
## Atualizar 
sudo dnf group update core
sudo dnf upgrade
## Cambiar a rama rawhide
sudo dnf --refresh --releasever=rawhide upgrade
sudo dnf --refresh --releasever=rawhide distro-sync
## Instalacion RpmFusion
sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
                 https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
## Instalar packetes mas usados 
sudo dnf install fontawesome-fonts-all langpacks-es vim-default-editor zsh wine-fonts lsd lm_sensors \
                 kate printer-driver-brlaser  --allowerasing
## Actualizacion de firmware
sudo fwupdmgr get-devices
sudo fwupdmgr refresh --force
sudo fwupdmgr get-updates -y
sudo fwupdmgr update -y
## Cambiar ffmpeg libre
sudo dnf swap ffmpeg-free ffmpeg --allowerasing
sudo dnf groupupdate multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin
sudo dnf groupupdate sound-and-video
sudo dnf install intel-media-driver
sudo dnf swap mesa-va-drivers mesa-va-drivers-freeworld
sudo dnf swap mesa-vdpau-drivers mesa-vdpau-drivers-freeworld
sudo dnf install gcc kernel-headers kernel-devel akmod-nvidia xorg-x11-drv-nvidia xorg-x11-drv-nvidia-libs
sudo dnf install nvidia-vaapi-driver libva-utils vdpauinfo
sudo cp -p /usr/share/X11/xorg.conf.d/nvidia.conf /etc/X11/xorg.conf.d/nvidia.conf

printf "%s" "
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
" | sudo tee -a /etc/sddm/Xsetup

sudo chsh -s /bin/zsh $USER
ln -s ~/Git/bak/config/zshrc ~/.zshrc
ln -s ~/Git/bak/config/zpreztorc ~/.zpreztorc

sudo curl -o /etc/yum.repos.d/softmaker.repo https://shop.softmaker.com/repo/softmaker.repo
echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null

sudo dnf distro-sync
sudo dnf install softmaker-freeoffice-2024 code-insiders
