#!/bin/sh
printf "%s" "
defaultyes=True
fastestmirror=True
max_parallel_downloads=20

" | sudo tee -a /etc/dnf/dnf.conf

sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

sudo dnf group update core

sudo dnf upgrade

sudo dnf autoremove -y

sudo fwupdmgr get-devices

sudo fwupdmgr refresh --force

sudo fwupdmgr get-updates -y

sudo fwupdmgr update -y

sudo fedora-third-party enable
sudo fedora-third-party refresh
sudo dnf swap ffmpeg-free ffmpeg --allowerasing
sudo dnf groupupdate multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin
sudo dnf groupupdate sound-and-video
sudo dnf install intel-media-driver
sudo dnf swap mesa-va-drivers mesa-va-drivers-freeworld
sudo dnf swap mesa-vdpau-drivers mesa-vdpau-drivers-freeworld
sudo dnf install nvidia-vaapi-driver
sudo dnf install vim-default-editor zsh --allowerasing
sudo dnf group install Multimedia
sudo dnf install gcc kernel-headers kernel-devel akmod-nvidia xorg-x11-drv-nvidia xorg-x11-drv-nvidia-libs

sudo cp -p /usr/share/X11/xorg.conf.d/nvidia.conf /etc/X11/xorg.conf.d/nvidia.conf

printf "%s" "
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
" | sudo tee -a /etc/sddm/Xsetup

sudo dnf install plasma-workspace-x11
sudo chsh -s /bin/zsh $USER
ln -s ~/Git/bak/config/zshrc ~/.zshrc
ln -s ~/Git/bak/config/zpreztorc ~/.zpreztorc
sudo dnf install plasma-workspace-x11
sudo wget -qO /etc/yum.repos.d/softmaker.repo https://shop.softmaker.com/repo/softmaker.repo
echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null
sudo dnf distro-sync
sudo dnf install softmaker-freeoffice-2021 code-insiders kate
sudo dnf install fontawesome\* langpacks-es
sudo dnf remove libreoffice\* ibus skanpage akregator kmail neochat kontact korganizer ktnef kaddressbook kcharselect kfind kgpg kmousetool kmouth kwrite filelight
